language: cpp
compiler:
  - gcc
os: linux
dist: trusty
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y valgrind
 - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
 - sudo tar xf release-1.7.0.tar.gz
 - cd googletest-release-1.7.0
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make -j8
 - sudo cp -a include/gtest /usr/include
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - which valgrind
 - cd "${TRAVIS_BUILD_DIR}"
 - ls -l
script: 
 - cd ut
 - sudo wget https://raw.githubusercontent.com/fkromer/catch_cmake_coverage/master/cmake/Modules/CodeCoverage.cmake
 - cmake -DBUILD_TESTS=ON .
 - make -j8
 - make -j8 xpjson_coverage
 - ctest
 - valgrind ./xpjson_ut
branches:
  only:
    - master
addons:
  apt:
    packages:
    - cmake
    - lcov
after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"